## Any words added to this list will be replaced by the variable censorChar in the chat
## this includes words that have this string in them
## For example "Class" will be censored since it contains the string 'ass'
## This will be fixed eventually :)
words:
  - 'ass'
  - 'shit'
  - 'fuck'

censorChar: "ඞ"